steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-backend", "./backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-frontend", "./frontend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-frontend"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-backend", "--image", "gcr.io/$PROJECT_ID/test-backend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "8000"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-frontend", "--image", "gcr.io/$PROJECT_ID/test-frontend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "80"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -euo pipefail
        # Attach secret to backend (use numeric project number required by Cloud Run)
        gcloud run services update test-backend --region=us-central1 --update-secrets=GROQ_API_KEY=projects/329621052662/secrets/GROQ_API_KEY:latest

        # Make services public invoker (ignore errors)
        gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-backend || true
        gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-frontend || true

        # Get the backend URL and set it on the frontend
        BACKEND_URL=$(gcloud run services describe test-backend --region=us-central1 --format='value(status.url)')
        echo "Backend URL: $$BACKEND_URL"
        gcloud run services update test-frontend --region=us-central1 --set-env-vars=VITE_API_URL="$$BACKEND_URL"

images:
  - "gcr.io/$PROJECT_ID/test-backend"
  - "gcr.io/$PROJECT_ID/test-frontend"

timeout: "1200s"
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-backend", "./backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-frontend", "./frontend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-frontend"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-backend", "--image", "gcr.io/$PROJECT_ID/test-backend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "8000"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-frontend", "--image", "gcr.io/$PROJECT_ID/test-frontend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "80"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -euo pipefail
        # Attach secret to backend (use numeric project number required by Cloud Run)
        gcloud run services update test-backend --region=us-central1 --update-secrets=GROQ_API_KEY=projects/329621052662/secrets/GROQ_API_KEY:latest

        # Make services public invoker (ignore errors)
        gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-backend || true
        gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-frontend || true

        # Get the backend URL and set it on the frontend
        BACKEND_URL=$(gcloud run services describe test-backend --region=us-central1 --format='value(status.url)')
        echo "Backend URL: $$BACKEND_URL"
        gcloud run services update test-frontend --region=us-central1 --set-env-vars=VITE_API_URL="$$BACKEND_URL"

images:
  - "gcr.io/$PROJECT_ID/test-backend"
  - "gcr.io/$PROJECT_ID/test-frontend"

timeout: "1200s"
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-backend", "./backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-frontend", "./frontend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-frontend"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-backend", "--image", "gcr.io/$PROJECT_ID/test-backend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "8000"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-frontend", "--image", "gcr.io/$PROJECT_ID/test-frontend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "80"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        steps:
          - name: "gcr.io/cloud-builders/docker"
            args: ["build", "-t", "gcr.io/$PROJECT_ID/test-backend", "./backend"]

          - name: "gcr.io/cloud-builders/docker"
            args: ["build", "-t", "gcr.io/$PROJECT_ID/test-frontend", "./frontend"]

          - name: "gcr.io/cloud-builders/docker"
            args: ["push", "gcr.io/$PROJECT_ID/test-backend"]

          - name: "gcr.io/cloud-builders/docker"
            args: ["push", "gcr.io/$PROJECT_ID/test-frontend"]

          - name: "gcr.io/cloud-builders/gcloud"
            entrypoint: "gcloud"
            args: ["run", "deploy", "test-backend", "--image", "gcr.io/$PROJECT_ID/test-backend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "8000"]

          - name: "gcr.io/cloud-builders/gcloud"
            entrypoint: "gcloud"
            args: ["run", "deploy", "test-frontend", "--image", "gcr.io/$PROJECT_ID/test-frontend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "80"]

          - name: "gcr.io/cloud-builders/gcloud"
            entrypoint: "bash"
            args:
              - -c
              - |
                set -euo pipefail
                # Attach secret to backend (use numeric project number required by Cloud Run)
                gcloud run services update test-backend --region=us-central1 --update-secrets=GROQ_API_KEY=projects/329621052662/secrets/GROQ_API_KEY:latest

                # Make services public invoker (ignore errors)
                gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-backend || true
                gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-frontend || true

                # Get the backend URL and set it on the frontend
                BACKEND_URL=$(gcloud run services describe test-backend --region=us-central1 --format='value(status.url)')
                echo "Backend URL: $$BACKEND_URL"
                gcloud run services update test-frontend --region=us-central1 --set-env-vars=VITE_API_URL="$$BACKEND_URL"

        images:
          - "gcr.io/$PROJECT_ID/test-backend"
          - "gcr.io/$PROJECT_ID/test-frontend"

        timeout: "1200s"
        # Attach secret to backend (use numeric project number required by Cloud Run)
        gcloud run services update test-backend --region=us-central1 --update-secrets=GROQ_API_KEY=projects/329621052662/secrets/GROQ_API_KEY:latest

        # Make services public invoker (ignore errors)
        gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-backend || true
        gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker test-frontend || true

        # Get the backend URL and set it on the frontend
        BACKEND_URL=$(gcloud run services describe test-backend --region=us-central1 --format='value(status.url)')
        echo "Backend URL: $$BACKEND_URL"
        gcloud run services update test-frontend --region=us-central1 --set-env-vars=VITE_API_URL="$$BACKEND_URL"

images:
  - "gcr.io/$PROJECT_ID/test-backend"
  - "gcr.io/$PROJECT_ID/test-frontend"

timeout: "1200s"
