steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-backend", "./backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/test-frontend", "./frontend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/test-frontend"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-backend", "--image", "gcr.io/$PROJECT_ID/test-backend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "8000"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["run", "deploy", "test-frontend", "--image", "gcr.io/$PROJECT_ID/test-frontend", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated", "--port", "80"]

images:
  - "gcr.io/$PROJECT_ID/test-backend"
  - "gcr.io/$PROJECT_ID/test-frontend"
timeout: "1200s"
